#!/usr/bin/env node

import { confirm, input, password, select } from "@inquirer/prompts";
import { randomBytes, randomUUID } from "crypto";
import { existsSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";
import process from "process";
import { spawn } from "child_process";
import dotenv from "dotenv";
import qrcode from "qrcode-terminal";

const QUICKSTART_COMPOSE_FILE = "docker-compose.quickstart.yml";
const REQUIRED_MARKERS = [
  QUICKSTART_COMPOSE_FILE,
  path.join("unicon-vote-backend", "package.json"),
  path.join("unicon-vote-frontend", "package.json"),
];

const colors = {
  bold: (text) => `\u001b[1m${text}\u001b[0m`,
  cyan: (text) => `\u001b[36m${text}\u001b[0m`,
  green: (text) => `\u001b[32m${text}\u001b[0m`,
  yellow: (text) => `\u001b[33m${text}\u001b[0m`,
  red: (text) => `\u001b[31m${text}\u001b[0m`,
  dim: (text) => `\u001b[2m${text}\u001b[0m`,
};

const HELP_TEXT = `Usage: univote [command]

Commands
  configure   Interactive quickstart wizard
  start       docker compose up -d --build
  stop        Stop containers without removing data
  down        docker compose down (keeps Mongo volume)
  restart     Restart quickstart services
  status      Show compose status and run connection checks
  logs        Follow backend/frontend logs
  qr          Print the admin login QR in the terminal
  doctor      Check Docker, boot persistence, and app health
  help        Show this message
`;

function section(title) {
  console.log(`\n${colors.bold(colors.cyan(`== ${title} ==`))}`);
}

function info(message) {
  console.log(`${colors.cyan("•")} ${message}`);
}

function success(message) {
  console.log(`${colors.green("✓")} ${message}`);
}

function warn(message) {
  console.log(`${colors.yellow("!")} ${message}`);
}

function fail(message) {
  console.error(`${colors.red("x")} ${message}`);
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function timestampForFileName() {
  const now = new Date();
  const pad = (value) => String(value).padStart(2, "0");

  return [
    now.getFullYear(),
    pad(now.getMonth() + 1),
    pad(now.getDate()),
    "-",
    pad(now.getHours()),
    pad(now.getMinutes()),
    pad(now.getSeconds()),
  ].join("");
}

function findRepoRoot(startDir) {
  let currentDir = path.resolve(startDir);

  while (true) {
    const hasAllMarkers = REQUIRED_MARKERS.every((marker) =>
      existsSync(path.join(currentDir, marker))
    );

    if (hasAllMarkers) {
      return currentDir;
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      return null;
    }
    currentDir = parentDir;
  }
}

function getEnvPath(repoRoot) {
  return path.join(repoRoot, ".env");
}

function loadExistingEnv(repoRoot) {
  const envPath = getEnvPath(repoRoot);

  if (!existsSync(envPath)) {
    return {};
  }

  return dotenv.parse(readFileSync(envPath, "utf8"));
}

function backupExistingEnv(repoRoot) {
  const envPath = getEnvPath(repoRoot);

  if (!existsSync(envPath)) {
    return null;
  }

  const backupPath = path.join(repoRoot, `.env.backup.${timestampForFileName()}`);
  writeFileSync(backupPath, readFileSync(envPath, "utf8"), "utf8");
  return backupPath;
}

function writeEnvFile(repoRoot, envValues) {
  const lines = [
    "# Generated by univote-cli",
    "",
    "# Quickstart",
    `JWT_SECRET=${envValues.JWT_SECRET}`,
    `ADMIN_UUID=${envValues.ADMIN_UUID}`,
    `ADMIN_PASSWORD=${envValues.ADMIN_PASSWORD}`,
    `MONGO_ROOT_USER=${envValues.MONGO_ROOT_USER}`,
    `MONGO_ROOT_PASSWORD=${envValues.MONGO_ROOT_PASSWORD}`,
    `CORS_ORIGIN=${envValues.CORS_ORIGIN}`,
    `SEED_SAMPLE_DATA=${envValues.SEED_SAMPLE_DATA}`,
    "",
    "# Optional: existing production compose / CI/CD",
    `DOCKERHUB_USERNAME=${envValues.DOCKERHUB_USERNAME || ""}`,
    `SERVER_DOMAIN=${envValues.SERVER_DOMAIN || ""}`,
    `SERVER_HOST=${envValues.SERVER_HOST || ""}`,
    "",
    "# Optional: game thumbnail upload (S3-compatible storage)",
    `S3_REGION=${envValues.S3_REGION || ""}`,
    `S3_BUCKET=${envValues.S3_BUCKET || ""}`,
    `S3_ACCESS_KEY_ID=${envValues.S3_ACCESS_KEY_ID || ""}`,
    `S3_SECRET_ACCESS_KEY=${envValues.S3_SECRET_ACCESS_KEY || ""}`,
    `S3_ENDPOINT=${envValues.S3_ENDPOINT || ""}`,
    `S3_PUBLIC_BASE_URL=${envValues.S3_PUBLIC_BASE_URL || ""}`,
    `S3_FORCE_PATH_STYLE=${envValues.S3_FORCE_PATH_STYLE || "false"}`,
    "",
  ];

  writeFileSync(getEnvPath(repoRoot), lines.join("\n"), "utf8");
}

function generateSecret(length = 32) {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
  const bytes = randomBytes(length);
  let result = "";

  for (let index = 0; index < length; index += 1) {
    result += chars[bytes[index] % chars.length];
  }

  return result;
}

function sanitizePublicUrl(value) {
  return value.trim().replace(/\/+$/, "");
}

function parseOrigins(value) {
  return value
    .split(",")
    .map((origin) => sanitizePublicUrl(origin))
    .filter(Boolean);
}

function validateUrlList(value, allowBlank = false) {
  if (allowBlank && !value.trim()) {
    return true;
  }

  const urls = parseOrigins(value);
  if (urls.length === 0) {
    return "하나 이상의 URL을 입력해주세요.";
  }

  for (const url of urls) {
    try {
      const parsed = new URL(url);
      if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
        return "http:// 또는 https:// 로 시작해야 합니다.";
      }
    } catch (_error) {
      return `유효한 URL 형식이 아닙니다: ${url}`;
    }
  }

  return true;
}

function validateEnvToken(value, label) {
  if (!value.trim()) {
    return `${label} 값을 입력해주세요.`;
  }

  if (/\s/.test(value)) {
    return `${label}에는 공백을 넣지 않는 것을 권장합니다.`;
  }

  if (value.includes("#")) {
    return `${label}에는 # 문자를 넣지 않는 것을 권장합니다.`;
  }

  return true;
}

function getPreferredPublicUrl(existingEnv) {
  const currentOrigins = parseOrigins(existingEnv.CORS_ORIGIN || "");
  if (currentOrigins.length > 0) {
    return currentOrigins[0];
  }

  const networkInterfaces = os.networkInterfaces();
  for (const addresses of Object.values(networkInterfaces)) {
    for (const address of addresses || []) {
      if (address.family === "IPv4" && !address.internal) {
        return `http://${address.address}`;
      }
    }
  }

  return "http://localhost";
}

function getAdditionalOrigins(existingEnv) {
  const currentOrigins = parseOrigins(existingEnv.CORS_ORIGIN || "");
  return currentOrigins.slice(1).join(", ");
}

function getDisplayLoginUrl(envValues) {
  const baseUrl = parseOrigins(envValues.CORS_ORIGIN || "")[0] || "http://localhost";
  return `${baseUrl}/login?uuid=${envValues.ADMIN_UUID}`;
}

function maskValue(value, visible = 4) {
  if (!value) {
    return "(비어 있음)";
  }

  if (value.length <= visible * 2) {
    return "*".repeat(value.length);
  }

  return `${value.slice(0, visible)}...${value.slice(-visible)}`;
}

function getDockerComposeArgs(extraArgs = []) {
  return ["compose", "-f", QUICKSTART_COMPOSE_FILE, ...extraArgs];
}

function runCommand(command, args, options = {}) {
  const { cwd, stdio = "pipe" } = options;

  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd,
      stdio,
      env: process.env,
    });

    let stdout = "";
    let stderr = "";

    if (stdio === "pipe") {
      child.stdout.on("data", (chunk) => {
        stdout += chunk.toString();
      });
      child.stderr.on("data", (chunk) => {
        stderr += chunk.toString();
      });
    }

    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout, stderr, code });
      } else {
        const error = new Error(
          stderr.trim() || stdout.trim() || `${command} ${args.join(" ")} failed`
        );
        error.code = code;
        reject(error);
      }
    });
  });
}

async function commandExists(command) {
  try {
    await runCommand(command, ["--version"]);
    return true;
  } catch (_error) {
    return false;
  }
}

async function printComposeStatus(repoRoot) {
  await runCommand("docker", getDockerComposeArgs(["ps"]), {
    cwd: repoRoot,
    stdio: "inherit",
  });
}

async function ensureEnvExists(repoRoot) {
  const envPath = getEnvPath(repoRoot);

  if (!existsSync(envPath)) {
    throw new Error(
      `.env 파일이 없습니다. 먼저 ${colors.bold("univote configure")} 를 실행해주세요.`
    );
  }
}

async function checkDockerBasics() {
  section("Docker 확인");

  await runCommand("docker", ["--version"]);
  success("docker 명령을 찾았습니다.");

  await runCommand("docker", ["compose", "version"]);
  success("docker compose 플러그인을 찾았습니다.");

  await runCommand("docker", ["info"]);
  success("Docker 데몬이 실행 중입니다.");
}

async function checkDockerAutostart() {
  if (process.platform !== "linux") {
    info("이 시스템은 Linux가 아니어서 Docker 부팅 자동 시작 점검을 건너뜁니다.");
    return { supported: false, enabled: false };
  }

  if (!(await commandExists("systemctl"))) {
    info("systemctl 이 없어 Docker 부팅 자동 시작 점검을 건너뜁니다.");
    return { supported: false, enabled: false };
  }

  try {
    await runCommand("systemctl", ["is-enabled", "docker"]);
    success("Docker 서비스가 부팅 시 자동 시작되도록 설정되어 있습니다.");
    return { supported: true, enabled: true };
  } catch (_error) {
    warn("Docker 서비스 자동 시작이 아직 활성화되지 않았습니다.");
    return { supported: true, enabled: false };
  }
}

async function maybeEnableDockerAutostart() {
  const status = await checkDockerAutostart();
  if (!status.supported || status.enabled) {
    return;
  }

  const shouldEnable = await confirm({
    message: "리붓 후에도 자동으로 올라오게 Docker 서비스를 부팅 시 시작할까요?",
    default: true,
  });

  if (!shouldEnable) {
    warn("Docker 자동 시작은 건너뛰었습니다. 필요하면 나중에 직접 활성화해주세요.");
    return;
  }

  const command = typeof process.getuid === "function" && process.getuid() === 0
    ? "systemctl"
    : "sudo";
  const args =
    command === "systemctl"
      ? ["enable", "--now", "docker"]
      : ["systemctl", "enable", "--now", "docker"];

  section("Docker 자동 시작 활성화");
  await runCommand(command, args, { stdio: "inherit" });
  success("Docker 서비스를 부팅 시 자동 시작하도록 설정했습니다.");
}

async function waitForHttpOk(url, timeoutMs = 90000) {
  const startedAt = Date.now();
  let lastError = null;

  while (Date.now() - startedAt < timeoutMs) {
    try {
      const response = await fetch(url);
      if (response.ok) {
        return response;
      }
      lastError = new Error(`HTTP ${response.status}`);
    } catch (error) {
      lastError = error;
    }

    await sleep(2000);
  }

  throw lastError || new Error(`Timed out waiting for ${url}`);
}

async function verifyQuickstart(repoRoot, envValues) {
  section("실행 확인");
  await printComposeStatus(repoRoot);

  const localFrontendUrl = "http://127.0.0.1";
  const localHealthUrl = "http://127.0.0.1:5001/api/health";
  const localAdminStatusUrl = `http://127.0.0.1:5001/api/auth/status/${envValues.ADMIN_UUID}`;

  const [healthResponse, adminStatusResponse] = await Promise.all([
    waitForHttpOk(localHealthUrl),
    waitForHttpOk(localAdminStatusUrl),
  ]);
  await waitForHttpOk(localFrontendUrl);

  const healthPayload = await healthResponse.json();
  const adminPayload = await adminStatusResponse.json();

  success(`프론트엔드가 ${localFrontendUrl} 에서 응답합니다.`);
  success(`백엔드 health 체크 성공: ${healthPayload.status} / Mongo ${healthPayload.mongo}`);
  success(`관리자 계정 확인 성공: ${adminPayload.name} (${adminPayload.uuid})`);
}

async function startQuickstart(repoRoot, envValues) {
  section("서비스 시작");
  await runCommand("docker", getDockerComposeArgs(["up", "-d", "--build"]), {
    cwd: repoRoot,
    stdio: "inherit",
  });
  success("quickstart 컨테이너를 시작했습니다.");
  await verifyQuickstart(repoRoot, envValues);
}

async function stopQuickstart(repoRoot) {
  section("서비스 중지");
  await runCommand("docker", getDockerComposeArgs(["stop"]), {
    cwd: repoRoot,
    stdio: "inherit",
  });
  success("컨테이너를 중지했습니다. 데이터는 유지됩니다.");
}

async function downQuickstart(repoRoot) {
  section("compose down");
  await runCommand("docker", getDockerComposeArgs(["down"]), {
    cwd: repoRoot,
    stdio: "inherit",
  });
  success("컨테이너를 내렸습니다. Mongo 볼륨은 유지됩니다.");
}

async function restartQuickstart(repoRoot, envValues) {
  section("서비스 재시작");
  await runCommand("docker", getDockerComposeArgs(["restart"]), {
    cwd: repoRoot,
    stdio: "inherit",
  });
  success("컨테이너를 재시작했습니다.");
  await verifyQuickstart(repoRoot, envValues);
}

async function showLogs(repoRoot) {
  section("로그");
  await runCommand("docker", getDockerComposeArgs(["logs", "-f", "backend", "frontend"]), {
    cwd: repoRoot,
    stdio: "inherit",
  });
}

function printAdminAccess(envValues) {
  const adminLoginUrl = getDisplayLoginUrl(envValues);

  section("관리자 접속");
  info(`메인 주소: ${parseOrigins(envValues.CORS_ORIGIN || "")[0] || "http://localhost"}`);
  info(`관리자 로그인 URL: ${adminLoginUrl}`);
  info(`관리자 비밀번호: ${envValues.ADMIN_PASSWORD}`);
  console.log("");
  qrcode.generate(adminLoginUrl, { small: true });
}

async function printQr(repoRoot) {
  await ensureEnvExists(repoRoot);
  const envValues = loadExistingEnv(repoRoot);
  printAdminAccess(envValues);
}

async function runDoctor(repoRoot) {
  await checkDockerBasics();
  await checkDockerAutostart();

  if (!existsSync(getEnvPath(repoRoot))) {
    warn(".env 파일이 아직 없어서 앱 health 체크는 건너뜁니다.");
    return;
  }

  const envValues = loadExistingEnv(repoRoot);
  try {
    await verifyQuickstart(repoRoot, envValues);
  } catch (error) {
    warn("앱 health 체크는 아직 통과하지 못했습니다.");
    warn(error.message);
  }
}

async function collectConfig(repoRoot) {
  const existingEnv = loadExistingEnv(repoRoot);
  const recommendedValues = {
    publicUrl: getPreferredPublicUrl(existingEnv),
    additionalOrigins: getAdditionalOrigins(existingEnv),
    jwtSecret: existingEnv.JWT_SECRET || generateSecret(48),
    adminUuid: existingEnv.ADMIN_UUID || randomUUID(),
    adminPassword: existingEnv.ADMIN_PASSWORD || generateSecret(16),
    mongoUser: existingEnv.MONGO_ROOT_USER || "unicon",
    mongoPassword: existingEnv.MONGO_ROOT_PASSWORD || generateSecret(20),
    seedSampleData: existingEnv.SEED_SAMPLE_DATA === "true",
  };

  section("UNIVOTE Quickstart Wizard");
  info(`작업 디렉토리: ${repoRoot}`);
  info("이 마법사는 .env를 만들고 quickstart compose를 바로 띄우는 흐름입니다.");

  const publicUrl = sanitizePublicUrl(
    await input({
      message: "사용자가 접속할 기본 주소를 입력하세요.",
      default: recommendedValues.publicUrl,
      validate: (value) => validateUrlList(value),
    })
  );

  const additionalOrigins = await input({
    message: "추가로 허용할 CORS_ORIGIN 이 있으면 쉼표로 입력하세요. 없으면 Enter.",
    default: recommendedValues.additionalOrigins,
    validate: (value) => validateUrlList(value, true),
  });

  const useRecommendedSecrets = await confirm({
    message: "관리자 UUID, 관리자 비밀번호, JWT, Mongo 비밀번호는 추천값을 그대로 사용할까요?",
    default: true,
  });

  let adminUuid = recommendedValues.adminUuid;
  let adminPassword = recommendedValues.adminPassword;
  let jwtSecret = recommendedValues.jwtSecret;
  let mongoUser = recommendedValues.mongoUser;
  let mongoPassword = recommendedValues.mongoPassword;

  if (!useRecommendedSecrets) {
    adminUuid = await input({
      message: "관리자 UUID",
      default: recommendedValues.adminUuid,
      validate: (value) => validateEnvToken(value, "관리자 UUID"),
    });
    adminPassword = await password({
      message: "관리자 비밀번호",
      mask: "*",
      validate: (value) => validateEnvToken(value, "관리자 비밀번호"),
    });
    jwtSecret = await password({
      message: "JWT 시크릿",
      mask: "*",
      validate: (value) => validateEnvToken(value, "JWT 시크릿"),
    });
    mongoUser = await input({
      message: "Mongo 루트 사용자",
      default: recommendedValues.mongoUser,
      validate: (value) => validateEnvToken(value, "Mongo 루트 사용자"),
    });
    mongoPassword = await password({
      message: "Mongo 루트 비밀번호",
      mask: "*",
      validate: (value) => validateEnvToken(value, "Mongo 루트 비밀번호"),
    });
  }

  const seedSampleData = await confirm({
    message: "실서버에 샘플 사용자/샘플 게임을 넣을까요?",
    default: recommendedValues.seedSampleData,
  });

  const configureStorage = await confirm({
    message: "관리자 화면에서 게임 썸네일 업로드를 쓰기 위해 S3 호환 스토리지를 지금 설정할까요?",
    default: Boolean(existingEnv.S3_BUCKET),
  });

  let s3Region = existingEnv.S3_REGION || "ap-northeast-2";
  let s3Bucket = existingEnv.S3_BUCKET || "";
  let s3AccessKeyId = existingEnv.S3_ACCESS_KEY_ID || "";
  let s3SecretAccessKey = existingEnv.S3_SECRET_ACCESS_KEY || "";
  let s3Endpoint = existingEnv.S3_ENDPOINT || "";
  let s3PublicBaseUrl = existingEnv.S3_PUBLIC_BASE_URL || "";
  let s3ForcePathStyle = existingEnv.S3_FORCE_PATH_STYLE || "false";

  if (configureStorage) {
    s3Region = await input({
      message: "S3_REGION",
      default: s3Region,
      validate: (value) => validateEnvToken(value, "S3_REGION"),
    });
    s3Bucket = await input({
      message: "S3_BUCKET",
      default: s3Bucket,
      validate: (value) => validateEnvToken(value, "S3_BUCKET"),
    });
    s3AccessKeyId = await input({
      message: "S3_ACCESS_KEY_ID",
      default: s3AccessKeyId,
      validate: (value) => validateEnvToken(value, "S3_ACCESS_KEY_ID"),
    });
    s3SecretAccessKey = await password({
      message: "S3_SECRET_ACCESS_KEY",
      mask: "*",
      validate: (value) => validateEnvToken(value, "S3_SECRET_ACCESS_KEY"),
    });
    s3Endpoint = await input({
      message: "S3_ENDPOINT (AWS S3면 비워도 됩니다)",
      default: s3Endpoint,
      validate: (value) => validateUrlList(value, true),
    });
    s3PublicBaseUrl = await input({
      message: "S3_PUBLIC_BASE_URL (예: https://cdn.example.com)",
      default: s3PublicBaseUrl,
      validate: (value) => validateUrlList(value),
    });
    s3ForcePathStyle = (await confirm({
      message: "S3_FORCE_PATH_STYLE=true 가 필요한 스토리지인가요?",
      default: s3ForcePathStyle === "true",
    }))
      ? "true"
      : "false";
  } else {
    s3Region = existingEnv.S3_REGION || "ap-northeast-2";
    s3Bucket = "";
    s3AccessKeyId = "";
    s3SecretAccessKey = "";
    s3Endpoint = "";
    s3PublicBaseUrl = "";
    s3ForcePathStyle = "false";
  }

  const envValues = {
    JWT_SECRET: jwtSecret,
    ADMIN_UUID: adminUuid,
    ADMIN_PASSWORD: adminPassword,
    MONGO_ROOT_USER: mongoUser,
    MONGO_ROOT_PASSWORD: mongoPassword,
    CORS_ORIGIN: [publicUrl, ...parseOrigins(additionalOrigins)].join(","),
    SEED_SAMPLE_DATA: seedSampleData ? "true" : "false",
    DOCKERHUB_USERNAME: existingEnv.DOCKERHUB_USERNAME || "",
    SERVER_DOMAIN: existingEnv.SERVER_DOMAIN || "",
    SERVER_HOST: existingEnv.SERVER_HOST || "",
    S3_REGION: s3Region,
    S3_BUCKET: s3Bucket,
    S3_ACCESS_KEY_ID: s3AccessKeyId,
    S3_SECRET_ACCESS_KEY: s3SecretAccessKey,
    S3_ENDPOINT: sanitizePublicUrl(s3Endpoint),
    S3_PUBLIC_BASE_URL: sanitizePublicUrl(s3PublicBaseUrl),
    S3_FORCE_PATH_STYLE: s3ForcePathStyle,
  };

  section("적용 예정 값");
  info(`기본 접속 주소: ${publicUrl}`);
  info(`관리자 로그인 URL: ${getDisplayLoginUrl(envValues)}`);
  info(`관리자 비밀번호: ${envValues.ADMIN_PASSWORD}`);
  info(`JWT 시크릿: ${maskValue(envValues.JWT_SECRET)}`);
  info(`Mongo 루트 사용자: ${envValues.MONGO_ROOT_USER}`);
  info(`Mongo 루트 비밀번호: ${maskValue(envValues.MONGO_ROOT_PASSWORD)}`);
  info(`샘플 데이터: ${envValues.SEED_SAMPLE_DATA}`);
  info(
    envValues.S3_BUCKET
      ? `게임 썸네일 업로드: 사용 (${envValues.S3_PUBLIC_BASE_URL || envValues.S3_BUCKET})`
      : "게임 썸네일 업로드: 미사용 (URL 직접 입력만)"
  );

  const shouldWrite = await confirm({
    message: ".env를 쓰고 quickstart를 시작할까요?",
    default: true,
  });

  if (!shouldWrite) {
    throw new Error("사용자가 설정 저장을 취소했습니다.");
  }

  const backupPath = backupExistingEnv(repoRoot);
  if (backupPath) {
    info(`기존 .env는 ${backupPath} 로 백업했습니다.`);
  }

  writeEnvFile(repoRoot, envValues);
  success(".env 파일을 갱신했습니다.");

  return envValues;
}

async function runConfigure(repoRoot) {
  const envValues = await collectConfig(repoRoot);
  await checkDockerBasics();
  await maybeEnableDockerAutostart();
  await startQuickstart(repoRoot, envValues);
  printAdminAccess(envValues);
  info("다음부터는 `univote status`, `univote logs`, `univote qr` 로 바로 관리할 수 있습니다.");
}

async function runInteractiveMenu(repoRoot) {
  const choice = await select({
    message: "무엇을 할까요?",
    choices: [
      { name: "빠른 설정 + 시작", value: "configure" },
      { name: "상태 확인", value: "status" },
      { name: "로그 보기", value: "logs" },
      { name: "재시작", value: "restart" },
      { name: "중지", value: "stop" },
      { name: "compose down", value: "down" },
      { name: "관리자 QR 보기", value: "qr" },
      { name: "진단 실행", value: "doctor" },
      { name: "종료", value: "exit" },
    ],
  });

  return choice;
}

async function runCommandFromName(commandName, repoRoot) {
  const envValues = existsSync(getEnvPath(repoRoot)) ? loadExistingEnv(repoRoot) : null;

  switch (commandName) {
    case "configure":
      await runConfigure(repoRoot);
      return;
    case "start":
      await ensureEnvExists(repoRoot);
      await checkDockerBasics();
      await maybeEnableDockerAutostart();
      await startQuickstart(repoRoot, envValues);
      printAdminAccess(envValues);
      return;
    case "stop":
      await ensureEnvExists(repoRoot);
      await stopQuickstart(repoRoot);
      return;
    case "down":
      await ensureEnvExists(repoRoot);
      await downQuickstart(repoRoot);
      return;
    case "restart":
      await ensureEnvExists(repoRoot);
      await restartQuickstart(repoRoot, envValues);
      printAdminAccess(envValues);
      return;
    case "status":
      await ensureEnvExists(repoRoot);
      await verifyQuickstart(repoRoot, envValues);
      printAdminAccess(envValues);
      return;
    case "logs":
      await ensureEnvExists(repoRoot);
      await showLogs(repoRoot);
      return;
    case "qr":
      await printQr(repoRoot);
      return;
    case "doctor":
      await runDoctor(repoRoot);
      return;
    case "help":
      console.log(HELP_TEXT);
      return;
    default:
      throw new Error(`알 수 없는 명령입니다: ${commandName}`);
  }
}

async function main() {
  const repoRoot = findRepoRoot(process.cwd());
  if (!repoRoot) {
    throw new Error(
      "UNICON Vote App 저장소 루트에서 실행해주세요. docker-compose.quickstart.yml 을 찾지 못했습니다."
    );
  }

  const commandName = process.argv[2];

  if (!commandName) {
    if (!process.stdin.isTTY) {
      console.log(HELP_TEXT);
      return;
    }

    const choice = await runInteractiveMenu(repoRoot);
    if (choice === "exit") {
      return;
    }

    await runCommandFromName(choice, repoRoot);
    return;
  }

  await runCommandFromName(commandName, repoRoot);
}

main().catch((error) => {
  fail(error.message || "알 수 없는 오류가 발생했습니다.");
  process.exitCode = 1;
});
